#pragma once
#include "Process.h"
#include "processMgr.h"
#include "../include/SFML/Graphics.hpp"
#include "windowProcess.h"




 /*! Processes input events such as keyboard, mouse etc

eventProcess captures all I/O events such as keyboard clicks,
mouse clicks and mouse motion. The events are then sent to the eventMgr. 
Observer classes can then pick up on these events .

 Events generated by this class:
 
 WindowClosed:
 generated when the window is closed
 data: NULL

\sa eventMgr, Observer
*/   
 class eventProcess : public Process{
 	sf::RenderWindow *window;
 	sf::Event event;

 	eventMgr &eventManager;

 	void _handleEvent();

 	void _handleWindowCloseEvent();

 	void _handleMouseButtonPressed();
 	void _handleMouseButtonReleased();

 	void _handleMouseMove();

 	void _handleKeyboardPressed();
 	void _handleKeyboardReleased();

 	void _handleMouseWheelMove();


 public:
 	eventProcess(processMgr &processManager, Settings &settings, eventMgr &_eventManager) :
 	Process("eventProcess"), eventManager(_eventManager){

 		windowProcess *windowProc = processManager.getProcess<windowProcess>(Hash::getHash("windowProcess"));

 		this->window = windowProc->getWindow();
 	}

 	/*! Processes events and sends them to eventMgr*/
 	void preUpdate();

};