#pragma once

#pragma once
#include "Process.h"
#include "processMgr.h"
#include "../include/SFML/Graphics.hpp"

#include "windowProcess.h"

/*
 Events generated by this class:
 

 

*/
class viewProcess : public Process{
	sf::RenderWindow *window;
	
	sf::View defaultView;

public:
	viewProcess(processMgr &processManager, Settings &settings, eventMgr &_eventManager) :
	 Process("viewProcess"){
		
	 	windowProcess *windowProc = processManager.getProcess<windowProcess>(Hash::getHash("windowProcess"));

		
		/*this->window = windowProc->getWindow();
		windowProc->entertain();
		*/

		defaultView.zoom(1.0 / 20.0);
	}

	virtual void Update(){
		window->setView(defaultView);
	};
	
};